name: QuotaWatch
options:
  bundleIdPrefix: com.quotawatch
  deploymentTarget:
    macOS: 26.2
targets:
  QuotaWatch:
    type: application
    platform: macOS
    deploymentTarget: "26.2"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.quotawatch.QuotaWatch
      MARKETING_VERSION: "0.1.0"
      CURRENT_PROJECT_VERSION: 1
      SWIFT_VERSION: "6.0"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ENABLE_PREVIEWS: YES
      INFOPLIST_FILE: QuotaWatch/Info.plist
      CODE_SIGN_ENTITLEMENTS: QuotaWatch/QuotaWatch.entitlements
      ENABLE_APP_SANDBOX: YES
    sources: QuotaWatch
    entitlements:
      path: QuotaWatch/QuotaWatch.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
    info:
      path: QuotaWatch/Info.plist
      properties:
        CFBundleName: QuotaWatch
        CFBundleDisplayName: QuotaWatch
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSMinimumSystemVersion: 26.2
        LSUIElement: true
        NSHumanReadableCopyright: ""

  QuotaWatchTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "26.2"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.quotawatch.QuotaWatchTests
      SWIFT_VERSION: "6.0"
      INFOPLIST_FILE: QuotaWatchTests/Info.plist
    sources: QuotaWatchTests
    dependencies:
      - target: QuotaWatch
